import type { Role } from "@/hooks/useRole";

export const ALLOWED_PAGES: Record<Role, string[]> = {
  superadmin: [
    "dashboard",
    "user-list",
    "negative-user",
    "d/w report",
    "withdrawReq",
    "depositReq",
    "tradList",
    "pending-order",
    "positions",
    "manualTL",
    "rejection-list",
    "trade-log-list",
    "position-log-list",
    "client",
    "download-bill",
    "account-report",
    "settlement",
    "profit-loss",
    "ledger-account-report",
    "user-auto-sq-alert",
    "transactions",
    "banner",
    "announcement",
    "rules&regulation",
    "statements",
    "reports",
    "payment",
    "view",
    "market-watch",
    "superadmin",
  ],
  master: [
    "dashboard",
    "user-list",
    "negative-user",
    "d/w report",
    "withdrawReq",
    "depositReq",
    "tradList",
    "pending-order",
    "positions",
    "manualTL",
    "rejection-list",
    "trade-log-list",
    "position-log-list",
    "client",
    "download-bill",
    "account-report",
    "settlement",
    "profit-loss",
    "ledger-account-report",
    "user-auto-sq-alert",
    "transactions",
    "banner",
    "announcement",
    "rules&regulation",
    "statements",
    "reports",
    "payment",
    "view",
    "market-watch",
    "master",
    "bank-details",
  ],
  unknown: [],
};

export const canAccess = (role: Role, pageKey: string) =>
  ALLOWED_PAGES[role]?.includes(pageKey);
